N: 30
adaptive_loss_mode: balanced
attn_resolutions:
- 16
backbone: ncsnpp
base_dir: preprocessing/dataset/stem-gmd/
batch_size: 8
c_in: '1'
c_out: '1'
c_skip: '0'
centered: true
ch_mult:
- 1
- 1
- 2
- 2
- 2
- 2
- 2
ctc_weight: 1000.0
data_module_cls: !!python/name:sgmse.data_module.SpecsDataModule ''
dummy: false
ema_decay: 0.999
eval_tag: ''
format: default
hop_length: 128
l1_weight: 0.001
loss_type: score_matching
loss_weighting: sigma^2
lr: 0.0001
max_hours: 10.0
midi_encoder: lstm_midi_encoder
n_fft: 510
network_scaling: null
normalize: noisy
num_eval_files: 10
num_frames: 256
num_res_blocks: 2
num_workers: 4
pesq_weight: 0.0
sampler_type: pc
sde: ouve
sigma_data: 0.1
sigma_max: 0.5
sigma_min: 0.05
spec_abs_exponent: 0.5
spec_factor: 0.15
sr: 16000
t_eps: 0.03
theta: 1.5
transform_type: exponent
use_ca: false
use_film: false
use_midi: false
verbose: false
window: hann
